### ISSUE TITLE
Gather Data

### ISSUE THREAD

**Issue by DanielYatali** [HackathonProjectss/LIfeStyleBot-Fast-API#2]
We will need data to add to the Vexter Agent specific to lifestyle.
Possible sources:

1. Public Websites
2. PDF
3. Other documents

- [x] Compile a list of resources that can be used to train the lifestyle bot

**Comment by sakram09** [comment]
*Public Websites:*

1. Health and wellness websites (e.g. WebMD, Healthline, Mayo Clinic)
2. Lifestyle blogs and articles (e.g. Medium, HuffPost, Lifehacker)
3. Social media platforms (e.g. Twitter, Instagram, Facebook)
4. Online forums and communities (e.g. Reddit, Quora, Stack Exchange)
5. Government health and wellness resources (e.g. CDC, NIH, USDA)

*PDF and Other Documents:*

1. Research papers and studies on lifestyle and wellness
2. eBooks and whitepapers on health and wellness topics
3. Government reports and data on lifestyle and wellness
4. Non-profit organization resources (e.g. American Heart Association, American Cancer Society)
5. Academic journals and publications (e.g. Journal of Lifestyle Medicine, American Journal of Preventive Medicine)

*Specific Resources:*

1. World Health Organization (WHO) - Global Recommendations on Physical Activity for Health
2. American Heart Association - Healthy Living Resources
3. Academy of Nutrition and Dietetics - EatRight Resources
4. National Sleep Foundation - Sleep Resources
5. Centers for Disease Control and Prevention (CDC) - Healthy Living Resources

*Data Sources:*

1. US Census Bureau - Demographic and socioeconomic data
2. Centers for Medicare and Medicaid Services (CMS) - Health data and statistics
3. National Center for Health Statistics (NCHS) - Health data and statistics
4. World Bank - Development and health data
5. Google Trends - Lifestyle and wellness search

**Comment by sakram09** [comment]
https://docs.google.com/document/d/10TsACPrV_QXf9wuRswq5Xny-wOqulJSYsxrrdysScJE/edit?usp=sharing

**Comment by sakram09** [comment]
All links are given in this document
